
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://hiycannkfygbhkvfcnsf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhpeWNhbm5rZnlnYmhrdmZjbnNmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTAwMTk5OTgsImV4cCI6MjA2NTU5NTk5OH0.tmASPBXv9zFEtTK1YmUODHo4iVudUW_6IO4q_Yb-Rjo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
